### ISSUE TITLE
Remove the Google Analytics code from config.yml

### ISSUE THREAD

**Issue by amitmerchant1990** [Grappus/grappus-blog#1]
Hi guys,

Creator of Reverie here. Just wanted to ask you to remove the Google Analytics code from the `config.yml` since traffic of your blog is coming into my analytics feed.

Thanks!

**Comment by gautamgahlawat** [comment]
Hi Amit,

Yea sure. Apologies for the inconvenience.

Best Regards,
Gautam Gahlawat

**Comment by amitmerchant1990** [comment]
Looks like the traffic is still coming from your blog. Would you please remove it as soon as possible?

**Comment by gautamgahlawat** [comment]
We have removed it from our side. Please check now.
